# fail2ban filter for Caddy excessive 4xx errors (brute force)
# INSTALL: sudo cp fail2ban-caddy-4xx.conf /etc/fail2ban/filter.d/caddy-4xx.conf

[Definition]
failregex = ^.*"remote_ip":"<HOST>".*"status":4\d\d.*$
ignoreregex = ^.*"status":404.*"uri":"/favicon.ico".*$
datepattern = "ts":{EPOCH}
