# fail2ban filter for Caddy auth failures
# INSTALL: sudo cp fail2ban-caddy-auth.conf /etc/fail2ban/filter.d/caddy-auth.conf

[Definition]
failregex = ^.*"remote_ip":"<HOST>".*"status":401.*$
            ^.*"remote_ip":"<HOST>".*"status":403.*$
ignoreregex =
datepattern = "ts":{EPOCH}
