// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5zJqeDVenc9ygUx2zyW2WLkczY6FLavI',
    appId: '1:168752018174:web:3886f632a089ee14d82baf',
    messagingSenderId: '168752018174',
    projectId: 'superparty-frontend',
    authDomain: 'superparty-frontend.firebaseapp.com',
    storageBucket: 'superparty-frontend.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5zJqeDVenc9ygUx2zyW2WLkczY6FLavI',
    appId: '1:168752018174:android:3886f632a089ee14d82baf',
    messagingSenderId: '168752018174',
    projectId: 'superparty-frontend',
    storageBucket: 'superparty-frontend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5zJqeDVenc9ygUx2zyW2WLkczY6FLavI',
    appId: '1:168752018174:ios:ce46b5786bc4c6f8d82baf',
    messagingSenderId: '168752018174',
    projectId: 'superparty-frontend',
    storageBucket: 'superparty-frontend.firebasestorage.app',
    iosBundleId: 'com.superpartybyai.superpartyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5zJqeDVenc9ygUx2zyW2WLkczY6FLavI',
    appId: '1:168752018174:ios:ce46b5786bc4c6f8d82baf',
    messagingSenderId: '168752018174',
    projectId: 'superparty-frontend',
    storageBucket: 'superparty-frontend.firebasestorage.app',
    iosBundleId: 'com.superpartybyai.superpartyApp',
  );
}
