[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 100
healthcheckInterval = 10

[env]
OPENAI_API_KEY = "<OPENAI_KEY_REDACTED>"
TWILIO_ACCOUNT_SID = "[REDACTED_TWILIO]"
TWILIO_AUTH_TOKEN = "5c6670d39a1dbf46d47ecdaa244b91d9"
TWILIO_PHONE_NUMBER = "+12182204425"
BACKEND_URL = "https://web-production-f0714.up.railway.app"
COQUI_API_URL = "https://web-production-00dca9.up.railway.app"
NODE_ENV = "production"
PORT = "5001"
